import sys
import io
import pandas as pd
import json
import numpy as np

def compile_data(output_filename):
    # 1. Load Source Data
    csv_data = """
| Type                | Driver                                    |   Frequency in literatures |   Percentage |
|:--------------------|:------------------------------------------|---------------------------:|-------------:|
| Individual behavior | Satisfaction with sensory characteristics |                         10 |    0.178571  |
| nan                 | Social norms                              |                          6 |    0.107143  |
| nan                 | Attitude towards food waste               |                          4 |    0.0714286 |
| nan                 | Economic level                            |                          3 |    0.0535714 |
| nan                 | Eating habits                             |                          2 |    0.0357143 |
| Canteen             | Duration of eating time                   |                          5 |    0.0892857 |
| nan                 | Menu planning                             |                          5 |    0.0892857 |
| nan                 | Portion size                              |                          5 |    0.0892857 |
| nan                 | Use of trays                              |                          3 |    0.0535714 |
| nan                 | Staff training                            |                          3 |    0.0535714 |
| nan                 | Food quality and palatability             |                          2 |    0.0357143 |
| nan                 | Canteen atmosphere                        |                          1 |    0.0178571 |
| Demographics        | Gender                                    |                          5 |    0.0892857 |
| nan                 | Age                                       |                          2 |    0.0357143 |
"""
    
    # Parse data
    df = pd.read_csv(io.StringIO(csv_data), sep="|")
    
    # Clean column names (remove whitespace)
    df.columns = [c.strip() for c in df.columns]
    
    # Remove the empty columns generated by the markdown pipe format
    if df.columns[0] == '' or 'Unnamed' in df.columns[0]:
        df = df.iloc[:, 1:]
    if df.columns[-1] == '' or 'Unnamed' in df.columns[-1]:
        df = df.iloc[:, :-1]

    # Remove the markdown separator row (contains '---')
    df = df[~df['Type'].astype(str).str.contains('---')]
    
    # Reset index
    df = df.reset_index(drop=True)

    # Clean string columns
    df['Type'] = df['Type'].astype(str).str.strip()
    df['Driver'] = df['Driver'].astype(str).str.strip()
    
    # Handle 'nan' strings if they were read as strings
    df['Type'] = df['Type'].replace({'nan': np.nan, 'NaN': np.nan})
    
    # Forward fill the 'Type' column
    df['Type'] = df['Type'].ffill()
    
    # Convert numeric columns
    df['Frequency in literatures'] = pd.to_numeric(df['Frequency in literatures'])
    df['Percentage'] = pd.to_numeric(df['Percentage'])
    
    # Rename for display to match image
    df['Type'] = df['Type'].replace('Individual behavior', 'Individual\nbehaviour')
    df['Type'] = df['Type'].replace('Demographics', 'Demographic')
    
    # Save to JSON
    data = df.to_dict(orient='records')
    output_data = {
        "scr_data": data,
        "der_data": []
    }
    with open(output_filename, 'w') as f:
        json.dump(output_data, f, indent=4)
    print(f"Data saved to {output_filename}")

if __name__ == "__main__":
    output_file = "bench/ground_truth_code/nature_2_output/174.json"
    if len(sys.argv) > 1:
        output_file = sys.argv[1]
    compile_data(output_file)
