import sys
import io
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import textwrap

def generate_chart(output_filename):
    # 1. Load Source Data
    csv_data = """
| Type                | Driver                                    |   Frequency in literatures |   Percentage |
|:--------------------|:------------------------------------------|---------------------------:|-------------:|
| Individual behavior | Satisfaction with sensory characteristics |                         10 |    0.178571  |
| nan                 | Social norms                              |                          6 |    0.107143  |
| nan                 | Attitude towards food waste               |                          4 |    0.0714286 |
| nan                 | Economic level                            |                          3 |    0.0535714 |
| nan                 | Eating habits                             |                          2 |    0.0357143 |
| Canteen             | Duration of eating time                   |                          5 |    0.0892857 |
| nan                 | Menu planning                             |                          5 |    0.0892857 |
| nan                 | Portion size                              |                          5 |    0.0892857 |
| nan                 | Use of trays                              |                          3 |    0.0535714 |
| nan                 | Staff training                            |                          3 |    0.0535714 |
| nan                 | Food quality and palatability             |                          2 |    0.0357143 |
| nan                 | Canteen atmosphere                        |                          1 |    0.0178571 |
| Demographics        | Gender                                    |                          5 |    0.0892857 |
| nan                 | Age                                       |                          2 |    0.0357143 |
"""
    
    # Parse data
    # Use sep='|' to parse the markdown table
    df = pd.read_csv(io.StringIO(csv_data), sep="|")
    
    # Clean column names (remove whitespace)
    df.columns = [c.strip() for c in df.columns]
    
    # Remove the empty columns generated by the markdown pipe format
    # Usually index 0 and -1 are empty strings or Unnamed
    if df.columns[0] == '' or 'Unnamed' in df.columns[0]:
        df = df.iloc[:, 1:]
    if df.columns[-1] == '' or 'Unnamed' in df.columns[-1]:
        df = df.iloc[:, :-1]

    # Remove the markdown separator row (contains '---')
    # We check the 'Type' column. It will be something like ':---'
    df = df[~df['Type'].astype(str).str.contains('---')]
    
    # Reset index
    df = df.reset_index(drop=True)

    # Clean string columns
    df['Type'] = df['Type'].astype(str).str.strip()
    df['Driver'] = df['Driver'].astype(str).str.strip()
    
    # Handle 'nan' strings if they were read as strings
    df['Type'] = df['Type'].replace({'nan': np.nan, 'NaN': np.nan})
    
    # Forward fill the 'Type' column
    df['Type'] = df['Type'].ffill()
    
    # Convert numeric columns
    df['Frequency in literatures'] = pd.to_numeric(df['Frequency in literatures'])
    
    # Rename for display to match image
    df['Type'] = df['Type'].replace('Individual behavior', 'Individual\nbehaviour')
    df['Type'] = df['Type'].replace('Demographics', 'Demographic')
    
    # 2. Prepare Data for Plotting
    
    # Group data for the inner ring
    inner_group = df.groupby('Type', sort=False)['Frequency in literatures'].sum()
    inner_labels = inner_group.index
    inner_values = inner_group.values
    
    # Calculate total for percentages
    total_freq = df['Frequency in literatures'].sum()
    
    # Colors
    # Individual (Red/Salmon), Canteen (Yellow/Gold), Demographic (Blue)
    c_inner_red = '#C06C6C'
    c_inner_yellow = '#D4B95E'
    c_inner_blue = '#5C97A8'
    
    inner_colors = [c_inner_red, c_inner_yellow, c_inner_blue]
    
    # Outer Ring Colors (Gradients)
    outer_colors = []
    
    # Custom palettes to match image better
    # Red group: Dark red to light pinkish
    reds = ['#C06C6C', '#CD7F7F', '#D99292', '#E5A5A5', '#F0B9B9']
    # Yellow group: Gold to pale yellow
    yellows = ['#D4B95E', '#DCC474', '#E3CF8A', '#EBD9A0', '#F2E4B6', '#F9EFCC', '#FFF9E2']
    # Blue group: Teal to light blue
    blues = ['#5C97A8', '#82B3C0']

    palette_map = {
        'Individual\nbehaviour': reds,
        'Canteen': yellows,
        'Demographic': blues
    }

    # Generate flattened color list for outer ring
    for i, (name, group) in enumerate(df.groupby('Type', sort=False)):
        count = len(group)
        base_palette = palette_map.get(name, [inner_colors[i]] * count)
        
        # If we don't have enough colors in manual palette, repeat last color
        if len(base_palette) < count:
            base_palette = base_palette + [base_palette[-1]] * (count - len(base_palette))
        
        outer_colors.extend(base_palette[:count])

    # 3. Plotting
    fig, ax = plt.subplots(figsize=(12, 10))
    
    # Chart parameters
    size = 0.35 # Width of rings
    inner_radius = 0.65
    outer_radius = 1.0
    
    # Matplotlib pie charts start at x-axis (0 deg). 
    # Image starts Individual Behaviour at 12 o'clock (90 deg) and goes Clockwise.
    start_angle = 90
    
    # --- Outer Ring (Drivers) ---
    wedges_outer, texts_outer = ax.pie(
        df['Frequency in literatures'], 
        radius=outer_radius, 
        colors=outer_colors, 
        startangle=start_angle,
        counterclock=False,
        wedgeprops=dict(width=size, edgecolor='w', linewidth=1)
    )
    
    # --- Inner Ring (Types) ---
    wedges_inner, texts_inner = ax.pie(
        inner_values, 
        radius=inner_radius, 
        colors=inner_colors, 
        startangle=start_angle,
        counterclock=False,
        wedgeprops=dict(width=size, edgecolor='w', linewidth=2) # Thicker white line between groups
    )
    
    # 4. Annotations and Labels
    
    # --- Inner Labels ---
    for i, w in enumerate(wedges_inner):
        ang = (w.theta2 - w.theta1)/2. + w.theta1
        y = np.sin(np.deg2rad(ang)) * (inner_radius - size/2)
        x = np.cos(np.deg2rad(ang)) * (inner_radius - size/2)
        
        pct = (inner_values[i] / total_freq) * 100
        label_text = f"{inner_labels[i]}\n{pct:.1f}%"
        
        # Text color white for contrast
        ax.text(x, y, label_text, ha='center', va='center', color='white', 
                fontsize=11, fontweight='normal')

    # --- Outer Labels (with lines) ---
    
    # Mapping specific labels to match image shortening if necessary
    label_map = {
        "Food quality and palatability": "Food quality",
        "Satisfaction with sensory characteristics": "Satisfaction with\nsensory characteristics",
        "Attitude towards food waste": "Attitude\ntowards\nfood waste"
    }
    
    for i, p in enumerate(wedges_outer):
        ang = (p.theta2 - p.theta1)/2. + p.theta1
        
        # Coordinates for the start of the line (on the wedge edge)
        y = np.sin(np.deg2rad(ang)) * outer_radius
        x = np.cos(np.deg2rad(ang)) * outer_radius
        
        # Coordinates for the text
        horizontalalignment = {-1: "right", 1: "left"}[int(np.sign(x))]
        
        # Adjust connection style based on position
        connectionstyle = f"angle,angleA=0,angleB={ang}"
        
        # Determine text position
        shift_factor = 1.25
        
        # Normalize angle to 0-360
        norm_ang = ang % 360
        
        xt = x * shift_factor
        yt = y * shift_factor
        
        # Manual tweaking for layout similar to image
        if 90 < norm_ang < 270: # Left side
            xt -= 0.1
        else: # Right side
            xt += 0.1
            
        driver_name = df['Driver'].iloc[i]
        driver_name = label_map.get(driver_name, driver_name)
        
        # Wrap text if not manually mapped with newlines
        if '\n' not in driver_name and len(driver_name) > 15:
            driver_name = textwrap.fill(driver_name, 15)
            
        pct_val = (df['Frequency in literatures'].iloc[i] / total_freq) * 100
        
        # Color of text matches the group color (roughly)
        text_color = '#885555' # Default reddish
        if i >= 5 and i < 12: # Canteen group
            text_color = '#C4A000' # Gold/Dark Yellow
        elif i >= 12: # Demographic
            text_color = '#367588' # Blue
            
        display_text = f"{driver_name}\n{pct_val:.1f}%"
        
        ax.annotate(display_text, xy=(x, y), xytext=(xt, yt),
                    horizontalalignment=horizontalalignment,
                    verticalalignment='center',
                    fontsize=10,
                    color=text_color,
                    arrowprops=dict(arrowstyle="-", color='gray', linewidth=0.5,
                                    connectionstyle=connectionstyle))

    # Add Figure Label 'a'
    ax.text(-0.05, 1.0, 'a', transform=ax.transAxes, fontsize=24, fontweight='bold')

    plt.tight_layout()
    plt.savefig(output_filename, dpi=300, bbox_inches='tight')
    print(f"Chart saved to {output_filename}")

if __name__ == "__main__":
    output_file = "output.png"
    if len(sys.argv) > 1:
        output_file = sys.argv[1]
    generate_chart(output_file)